### ISSUE TITLE
Aide sur le filtre par heure

### ISSUE THREAD

**Issue by Loursbis** [DavidBourgon/Projet-info#1]
Bonjour @xlecureuil 

Concernant l'aide que tu m'as demandé, j'ai l'impression que ce que tu as fait fonctionne. Je veux bien que tu m'envoies ici des exemples de cas ou il y a un problème, merci !

https://github.com/DavidBourgon/Projet-info/blob/66f7c69ff361d8698b294b26831c43d631d55f76/Xavier/bordel_xavier.py#L193

**Comment by xlecureuil** [comment]
Merci pour votre réponse oui, j'ai reussi à le corriger merci bcp pour votre reponse
